\c yogaposes_dev;

INSERT INTO yogaposes (name, level, sanskrit, instructions, benefits, website, image_link, is_favorite) VALUES

('easy pose', 'basic', 'sukhasana', 'https://www.yogabasics.com/asana/easy-pose/#:~:text=Instructions,a%20seated%20position', 'Easy pose is a comfortable seated position for meditation. This pose open the hips, lengthens the spine and promotes groundedness and inner calm.', 'https://www.yogabasics.com/asana/easy-pose/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/11/easypose_9628.jpg?w=700&ssl=1', false),
('corpse pose', 'basic', 'shavasana', 'https://www.yogabasics.com/asana/corpse/#:~:text=Instructions,on%20your%20back%2C', 'Corpse pose is essential to practice at the end of every yoga practice. This posture rejuvenates the body, mind and spirit while reducing stress and tension.', 'https://www.yogabasics.com/asana/corpse/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/11/Shavasana_9884.jpg?w=700&ssl=1', true),
('cat tilt', 'basic', 'marjariasanna', 'https://www.yogabasics.com/asana/cat-tilt-pose/#:~:text=Instructions,From%20Table%20pose%2C', 'Cat pose stretches the middle to upper back and shoulders.', 'https://www.yogabasics.com/asana/cat-tilt-pose/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/11/cat_9646.jpg?w=700&ssl=1', true),
('downward facing dog', 'beginner', 'Adho Mukha Shvasana', 'https://www.ekhartyoga.com/resources/yoga-poses/downward-facing-dog-pose#:~:text=Step%20by%20step,above%20your%20wrists.', 'Strengthens the whole body -upper body, arms, shoulders, abdomen and legs. Stretches the back of the body, ankles, calves, hamstrings, spine. Calms the mind. Stimulates blood circulation.', 'https://www.ekhartyoga.com/resources/yoga-poses/downward-facing-dog-pose', 'https://www.ekhartyoga.com/media/images/articles/content/Downward-Facing-Dog-Pose-Adho-Mukha-Svanasana.jpg', true),
('warrior 1', 'beginner', 'virabhadrasana', 'https://www.yogabasics.com/asana/warrior-i/%23:~:text=Instructions,the%20right%20ankle', 'Warrior I strengthens the legs, opens the hips and chest and stretches the arms and legs. Warrior I develops concentration, balance and groundedness. This pose improves circulation and respiration and energizes the entire body.', 'https://www.yogabasics.com/asana/warrior-i/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/12/warrior1_9429.jpg?w=700&ssl=1', true),
('upward forward fold', 'beginner', 'urdhva uttanasana', 'https://www.yogabasics.com/asana/upward-forward-fold/#:~:text=Instructions,the%20back%20flat.', 'Upward forward fold lengthens and aligns the spinal column, and stimulates the nervous system. This posture opens the chest and stretches the backs of the legs and the back muscles.', 'https://www.yogabasics.com/asana/upward-forward-fold/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/12/UpForFold_9713.jpg?w=700&ssl=1', false),
('chair pose', 'beginner', 'utkatasana', 'https://www.yogabasics.com/asana/chair/#:~:text=Instructions,palms%20facing%20down.', 'Chair pose strongly strengthens the lower body while stretching the upper back. This posture invigorates and energizes the whole body.', 'https://www.yogabasics.com/asana/chair/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/12/StandSquat_9469.jpg?w=700&ssl=1', true),
('half prayer twist', 'basic', 'ardha namaskar parsvakonasana', 'https://www.yogabasics.com/asana/half-prayer-twist/#:~:text=Next-,Instructions,-1.%20From', 'Half prayer twist opens the chest and hips, stretches the back muscles, and nourishes and realigns the spine.', 'https://www.yogabasics.com/asana/half-prayer-twist/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/11/half-prayer-twist1.jpg?w=700&ssl=1', true),
('tree pose', 'beginner', 'vrikshasana', 'https://www.yogabasics.com/asana/easy-pose/#:~:text=Instructions,up%20or%20down.', 'Tree pose increases balance, focus, memory and concentration and strengthens the ankles and knees.', 'https://www.yogabasics.com/asana/tree/', 'https://i0.wp.com/www.yogabasics.com/yogabasics2017/wp-content/uploads/2013/12/tree_9463.jpg?w=700&ssl=1', true),
('childs pose', 'basic', 'balasana', 'https://www.everydayyoga.com/blogs/guides/how-to-do-child_s-pose-in-yoga#:~:text=before%20practicing%20yoga.-,Instructions,-Begin%20on%20your', 'Child pose calms the body, mind and spirit and stimulates the third eye point. Child pose gently stretches the low back, massages and tones the abdominal organs, and stimulates digestion and elimination. It helps relieve back and neck pain and muscular tension.', 'https://www.everydayyoga.com/blogs/guides/how-to-do-child_s-pose-in-yoga', 'https://photos.cdn-outlet.com/yo-images/userfiles/image/yoga_childspose_01_300x350.jpg
', true);